### ISSUE TITLE
Automatic state signing

### ISSUE THREAD

**Issue by marcperrinp** [nash-io/api-client-typescript#6]
Hi,

I see the following in the Readme, section "State signing":

> In special cases where a user has more than one client process running at once which is placing a high volume of orders, it is advisable to take a more custom approach.

Could you please define "_high volume of orders_"?

I removed the call to `getSignAndSyncStates` as per [Jan's suggestion](https://gitlab.com/nash-io-public/nash-protocol/-/issues/3#note_364823566). Can I run into trouble if I have multiple client processes and say, a couple orders per second at times?

**Comment by localhuman** [comment]
The main issue is if you're placing more than 100 orders every couple of seconds.   
You'll be able to tell if you're running into this issue if you are seeing logs like: `Could not sign states: Some states to be found were not signed`.  This happens when multiple clients are trying to sync states at the same time.

**Comment by marcperrinp** [comment]
Perfect, thanks! I've added this error to my list of handled errors and will be on the lookout if ever that happens 🙏
